# Generated by Django 6.0.5 on 2026-05-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movielanguages_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielanguages',
            old_name='model',
            new_name='movie',
        ),
    ]
